### ISSUE TITLE
gpg key not on keyservers

### ISSUE THREAD

**Issue by NicoHood** [bobsaintcool/mooltipass-udev#1]
You should publish the gpg key on a keyserver, as I cannot find it anywhere. Please do so and post the full fingerprint in the readme.

**Comment by bobsaintcool** [comment]
I don't rely on PGP key servers.

It seems you upload my key for me[0].

[0] https://aur.archlinux.org/packages/mooltipass-udev/#news

**Comment by enricostano** [comment]
I still get the key error:
```
==> Verifying source file signatures with gpg...
    mooltipass-udev-2017021102.tar.gz ... FAILED (unknown public key DCD99CC69BFC6A5C)
==> ERROR: One or more PGP signatures could not be verified!
```

**Comment by bobsaintcool** [comment]
Please see my answer on you comment of the Arch Linux [AUR package](https://aur.archlinux.org/packages/mooltipass-udev#comment_id=600196)
