### ISSUE TITLE
Missing rule

### ISSUE THREAD

**Issue by Hypoon** [bobsaintcool/mooltipass-udev#2]
This appears to be out of sync with [https://github.com/mooltipass/moolticute/blob/master/data/moolticute.sh](https://github.com/mooltipass/moolticute/blob/master/data/moolticute.sh). There's one extra line there which is not here:
`SUBSYSTEM=="hidraw", KERNELS=="*1209:4321*", MODE="0660", SYMLINK+="mooltipass_keyboard", TAG+="uaccess", TAG+="udev-acl"`

**Comment by bobsaintcool** [comment]
@limpkin  can you confirm that this rule is really needed and that it relate to bluetooth keyboard exposed by minible?

/cc @limpkin

**Comment by limpkin** [comment]
@bobsaintcool it does look to be correct, this udev rule is for bluetooth (looking at the blame: https://github.com/mooltipass/moolticute/blame/master/data/moolticute.sh#L49)

**Comment by bobsaintcool** [comment]
Saw this as well but I'm not sure it is really needed, can you assert that the actual udev rule is not enough to work with the bluetooth keyboard?

If not you may create a pull request and merge it into master with [this branch](https://github.com/mooltipass/mooltipass-udev/tree/feature/bob%2Fudev_ble_keyboard)

**Comment by principis** [comment]
Can confirm that this rule is needed.

**Comment by bobsaintcool** [comment]
Thanks for the heads up @principis
